backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "static/assets/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - label: "Single Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/_index.md"
        fields:
          - label: "Slider Images"
            name: "slides"
            widget: "list"
            field: {label: Image, name: image, widget: image}
          - {label: Title, name: title, widget: string}
          - {label: BrandFX Subheading, name: brandfx_subhead, widget: string} 
          - {label: BrandFX Description, name: brandfx_desc, widget: string} 
          - {label: SignFX Subheading, name: signfx_subhead, widget: string} 
          - {label: SignFX Description, name: signfx_desc, widget: string} 
          - {label: VehicleFX Subheading, name: vehiclefx_subhead, widget: string} 
          - {label: VehicleFX Description, name: vehiclefx_desc, widget: string}  
          - {label: DisplayFX Subheading, name: displayfx_subhead, widget: string} 
          - {label: DisplayFX Description, name: displayfx_desc, widget: string}
          - {label: Recent Works Image 1, name: image_1, widget: image}   
          - {label: Description for image 1, name: description_1, widget: string}
          - {label: Recent Works Image 2, name: image_2, widget: image}   
          - {label: Description for image 2, name: description_2, widget: string} 
          - {label: Recent Works Image 3, name: image_3, widget: image}   
          - {label: Description for image 3, name: description_3, widget: string}
          - {label: Bottom Heading, name: bottom_heading, widget: string} 
          - {label: Bottom Description, name: bottom_desc, widget: string} 
          - {label: Address Line 1, name: address_1, widget: string} 
          - {label: Address Line 2, name: address_2, widget: string}  
          - {label: Address Line 3, name: address_3, widget: string}  
          - {label: Phone, name: phone, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "About"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string} 
          - {label: Description, name: desc, widget: string}
      - label: "Gallery"
        name: "gallery"
        file: "content/gallery.md"
        fields:
          - label: "All Images"
            name: "gallery"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "description", name: "description", widget: "string"}
              - {label: "Category", name: "category", widget: "select", options: ["brandingfx", "displayfx", "signfx", "vehiclefx"]}  
      - label: "Brand Image Fx"
        name: "brandingfx"
        file: "content/brandingfx/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Introduction", name: "intro", widget: "string"}
          - {label: "Recent 1", name: "recent_1", widget: "image"}
          - {label: "Recent 2", name: "recent_2", widget: "image"}
          - {label: "Recent 3", name: "recent_3", widget: "image"}
          - {label: "Recent 4", name: "recent_4", widget: "image"}
          - {label: "Recent 5", name: "recent_5", widget: "image"}
          - {label: "Recent 6", name: "recent_6", widget: "image"}
          - {label: "Recent 7", name: "recent_7", widget: "image"}
          - {label: "Recent 8", name: "recent_8", widget: "image"}
          - label: "Middle section"
            name: "section_2"
            fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "description", widget: "string"}
          - {label: "USP 1 heading", name: "usp_heading_1", widget: "string"}
          - {label: "USP 1 body", name: "usp_body_1", widget: "string"}
          - {label: "USP 2 heading", name: "usp_heading_2", widget: "string"}
          - {label: "USP 2 body", name: "usp_body_2", widget: "string"}
          - {label: "USP 3 heading", name: "usp_heading_3", widget: "string"}
          - {label: "USP 3 body", name: "usp_body_3", widget: "string"}
